apiVersion: v1
kind: Service
metadata:
  name: php-service
  labels:
    app: php
spec:
  ports:
  - port: 80
    nodePort: 30000          
  selector:
    app: main
    tier: cicd
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-claim
  labels:
    app: main
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-container
  labels:
    app: main
spec:
  selector:
    matchLabels:
      app: main
      tier: cicd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: main
        tier: cicd
    spec:
      containers:
      - image: omprakash1234/php
        name: image-name
        ports:
        - containerPort: 80
          name: port-name
        volumeMounts:
        - name: web-vol
          mountPath: /var/www/html
      volumes:
      - name: web-vol
        persistentVolumeClaim:
          claimName: pod-claim
